run:
  timeout: 3m
  tests: true
  skip-dirs:
    - frontend
    - docs
    - examples
    - migrations
    - .github

linters:
  disable-all: true
  enable:
    - govet
    - gofmt
    - goimports
    - gocyclo
    - gosimple
    - staticcheck
    - ineffassign
    - misspell
    - errcheck

issues:
  exclude-use-default: false
