name: synap

services:
  backend:
    image: ${IMAGE:-ghcr.io/${GHCR_OWNER:-soaringjerry}/synap-backend:latest}
    # Alternatively build locally:
    # build: .
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - SYNAP_ADDR=:8080
      - SYNAP_DB_PATH=/data/synap.db
    volumes:
      - synap-data:/data

volumes:
  synap-data:
