// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqldb

import (
	"database/sql"
	"time"
)

type AuditLog struct {
	ID     int64
	Ts     time.Time
	Actor  string
	Action string
	Target sql.NullString
	Note   sql.NullString
}

type ConsentRecord struct {
	ID       string
	ScaleID  string
	Version  sql.NullString
	Choices  sql.NullString
	Locale   sql.NullString
	SignedAt time.Time
	Hash     sql.NullString
}

type E2eeResponse struct {
	ResponseID     string
	ScaleID        string
	Ciphertext     string
	Nonce          sql.NullString
	AadHash        sql.NullString
	EncDek         sql.NullString
	PmkFingerprint sql.NullString
	CreatedAt      time.Time
	SelfToken      sql.NullString
}

type Item struct {
	ID                string
	ScaleID           string
	ReverseScored     int64
	StemI18n          sql.NullString
	Type              sql.NullString
	OptionsI18n       sql.NullString
	PlaceholderI18n   sql.NullString
	MinValue          sql.NullInt64
	MaxValue          sql.NullInt64
	StepValue         sql.NullInt64
	Required          int64
	LikertLabelsI18n  sql.NullString
	LikertShowNumbers int64
	Position          int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Participant struct {
	ID        string
	Email     sql.NullString
	SelfToken sql.NullString
	ConsentID sql.NullString
	CreatedAt time.Time
}

type ProjectKey struct {
	ScaleID     string
	Fingerprint string
	Algorithm   string
	Kdf         sql.NullString
	PublicKey   string
	CreatedAt   time.Time
	Disabled    int64
}

type Response struct {
	ParticipantID string
	ItemID        string
	ScaleID       string
	RawValue      sql.NullInt64
	ScoreValue    sql.NullInt64
	SubmittedAt   time.Time
	RawJson       sql.NullString
}

type Scale struct {
	ID                string
	TenantID          string
	Points            int64
	Randomize         int64
	NameI18n          sql.NullString
	ConsentI18n       sql.NullString
	CollectEmail      sql.NullString
	E2eeEnabled       int64
	Region            sql.NullString
	TurnstileEnabled  int64
	ItemsPerPage      sql.NullInt64
	ConsentConfig     sql.NullString
	LikertLabelsI18n  sql.NullString
	LikertShowNumbers int64
	LikertPreset      sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Tenant struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

type TenantAiConfig struct {
	TenantID      string
	OpenaiKey     sql.NullString
	OpenaiBase    sql.NullString
	AllowExternal int64
	StoreLogs     int64
	UpdatedAt     time.Time
}

type User struct {
	ID        string
	Email     string
	PassHash  []byte
	TenantID  string
	CreatedAt time.Time
}
