name: Release

on:
  release:
    types: [published]

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build Linux AMD64
        run: |
          GOOS=linux GOARCH=amd64 go build -o synap_linux_amd64 ./cmd/server
      - name: Build macOS ARM64
        run: |
          GOOS=darwin GOARCH=arm64 go build -o synap_darwin_arm64 ./cmd/server
      - name: Build Windows AMD64
        run: |
          GOOS=windows GOARCH=amd64 go build -o synap_windows_amd64.exe ./cmd/server
      - name: Upload assets to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            synap_linux_amd64
            synap_darwin_arm64
            synap_windows_amd64.exe
